apiVersion: v1
kind: Service
metadata:
  name: prom-service
  labels: 
    run: prom-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus
